language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper # for Qt5
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo apt-get update
  - sudo apt-get install -qq ubuntu-sdk libc6:i386
script:
  - qmake CuteMarkEd.pro
  - make         