language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo apt-get update
  - sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qttools5-dev-tools libhunspell-dev
before_script:
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_cs.ts -qm app/translations/cutemarked_cs.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_de.ts -qm app/translations/cutemarked_de.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_el.ts -qm app/translations/cutemarked_el.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_es.ts -qm app/translations/cutemarked_es.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_fr.ts -qm app/translations/cutemarked_fr.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_ja.ts -qm app/translations/cutemarked_ja.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_pt_BR.ts -qm app/translations/cutemarked_pt_BR.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_ru.ts -qm app/translations/cutemarked_ru.qm
  - qtchooser -run-tool=lrelease -qt=qt5 app/translations/cutemarked_zh_CN.ts -qm app/translations/cutemarked_zh_CN.qm
script:
  - cd 3rdparty/discount && ./configure.sh && make && sudo make install ; cd ../..
  - cd 3rdparty/hoedown && qtchooser -run-tool=qmake -qt=qt5 hoedown.pro && make && sudo make install ; cd ../.. 
  - qtchooser -run-tool=qmake -qt=qt5 CuteMarkEd.pro  
  - make
  - make check
           
