language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper # for Qt5
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -qq ubuntu-sdk libc6:i386 libgstreamer-plugins-base0.10 libgstreamer-plugins-base0.10-dev libhunspell-dev cmake
before_script:
  - lrelease app/translations/cutemarked_cs.ts -qm app/translations/cutemarked_cs.qm
  - lrelease app/translations/cutemarked_de.ts -qm app/translations/cutemarked_de.qm
  - lrelease app/translations/cutemarked_el.ts -qm app/translations/cutemarked_el.qm
  - lrelease app/translations/cutemarked_zh_CN.ts -qm app/translations/cutemarked_zh_CN.qm
script:
  - cd 3rdparty/discount && ./configure.sh && make && sudo make install ; cd ../..
  - cd 3rdparty/hoedown && qmake QMAKE_CXX=$CXX hoedown.pro && make && sudo make install ; cd ../.. 
  - cd 3rdparty/qoembed && mkdir build && cmake .. && make && cd ../..
  - qmake QMAKE_CXX=$CXX CuteMarkEd.pro
  - make
  - make check
           